#!/usr/bin/env python3
"""
artifact_beacon.py — File-system watcher for AI-generated artifacts.

Walks configurable paths and looks for provenance markers:

  • C2PA metadata (`.c2pa` sidecars or embedded JUMBF; we detect the file
    extension and the JUMBF/CAI magic strings inside binary headers)
  • "Generated by [AI model]" plain-text headers in source files
  • `.ai`/`.assistant` frontmatter in markdown and YAML files

For every match, the beacon emits one signed receipt with the artifact
path, sha256 digest of the first 1 MiB (for cheap fingerprinting), and
the matched marker type. Files themselves are never copied or uploaded.

Usage:
    python artifact_beacon.py --path ./docs --path ./content
    python artifact_beacon.py --path . --max-depth 4
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Iterable

from _common import append_receipt, make_receipt, sign_receipt

C2PA_MAGIC = b"c2pa"
JUMBF_MAGIC = b"jumb"
TEXT_MARKERS = [
    b"Generated by",
    b"<!-- ai:",
    b"<!-- assistant:",
    b"# ai:",
    b"# assistant:",
]
FRONTMATTER_KEYS = ("ai:", "assistant:", "generated_by:", "model:")

TEXT_EXTS = {
    ".md", ".markdown", ".txt", ".rst", ".html", ".htm", ".py", ".js",
    ".ts", ".tsx", ".jsx", ".yaml", ".yml", ".json", ".toml",
}
BINARY_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".mp4", ".mp3", ".wav", ".pdf"}


def iter_files(roots: list[Path], max_depth: int) -> Iterable[Path]:
    for root in roots:
        root = root.resolve()
        if not root.exists():
            continue
        base_depth = len(root.parts)
        for p in root.rglob("*"):
            if not p.is_file():
                continue
            if len(p.parts) - base_depth > max_depth:
                continue
            yield p


def sha256_head(path: Path, n: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    try:
        with path.open("rb") as fh:
            h.update(fh.read(n))
    except OSError:
        return ""
    return "sha256:" + h.hexdigest()


def scan_file(path: Path) -> dict[str, str] | None:
    ext = path.suffix.lower()
    if path.with_suffix(path.suffix + ".c2pa").exists() or ext == ".c2pa":
        return {"marker": "c2pa_sidecar"}
    try:
        size = path.stat().st_size
    except OSError:
        return None
    if size == 0:
        return None
    try:
        head = path.read_bytes()[:8192]
    except OSError:
        return None

    if ext in BINARY_EXTS:
        if C2PA_MAGIC in head or JUMBF_MAGIC in head:
            return {"marker": "c2pa_embedded"}
        return None

    if ext in TEXT_EXTS or ext == "":
        for marker in TEXT_MARKERS:
            if marker in head:
                return {"marker": "text_provenance_header"}
        try:
            text_head = head.decode("utf-8", errors="ignore")
        except UnicodeDecodeError:
            return None
        if text_head.startswith("---"):
            front, _, _ = text_head[3:].partition("\n---")
            for key in FRONTMATTER_KEYS:
                if key in front:
                    return {"marker": "frontmatter"}
    return None


def emit_receipt(path: Path, finding: dict[str, str]) -> None:
    digest = sha256_head(path)
    try:
        size = path.stat().st_size
    except OSError:
        size = 0
    receipt = make_receipt(
        event_type="discovery.model.found",
        subject=f"artifact://{path}",
        action="artifact_beacon.provenance_marker_detected",
        evidence={
            "path": str(path),
            "marker": finding["marker"],
            "size_bytes": size,
            "head_sha256": digest,
        },
        environment="on_prem",
    )
    sign_receipt(receipt)
    append_receipt(receipt)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("--path", action="append", type=Path, default=[], help="Path to scan (repeatable)")
    p.add_argument("--max-depth", type=int, default=8, help="Max directory recursion depth (default 8)")
    args = p.parse_args(argv)

    roots = args.path or [Path(".")]
    print(f"[artifact_beacon] scanning {len(roots)} root(s) up to depth {args.max_depth}")

    scanned = 0
    matched = 0
    for path in iter_files(roots, args.max_depth):
        scanned += 1
        finding = scan_file(path)
        if finding:
            emit_receipt(path, finding)
            matched += 1
    print(f"[artifact_beacon] {scanned} files scanned, {matched} provenance markers found")
    return 0


if __name__ == "__main__":
    sys.exit(main())
