#!/usr/bin/env python3
"""
build_mapping.py — Auto-derive scoring/mapping.yaml from the framework registry.

For every evidence_type that appears across the 23 frameworks, collect the
list of `framework_id.control_id` pairs that reference it. The resulting
YAML is the default mapping used by scoring/engine.py.

Operators are expected to tune the mapping; this is the seed.

Usage:
    python build_mapping.py --frameworks ../frameworks --out mapping.yaml
"""

from __future__ import annotations

import argparse
import glob
import os
from collections import defaultdict
from pathlib import Path

import yaml


def build(frameworks_dir: Path) -> dict[str, list[str]]:
    mapping: dict[str, list[str]] = defaultdict(list)
    for path in sorted(glob.glob(str(frameworks_dir / "*.yaml"))):
        if os.path.basename(path) == "index.yaml":
            continue
        framework = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
        fid = framework["framework_id"]
        for control in framework.get("controls", []):
            cid = control["id"]
            for ev in control.get("evidence_types", []):
                mapping[ev].append(f"{fid}.{cid}")
    # Deterministic ordering
    return {k: sorted(set(v)) for k, v in sorted(mapping.items())}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("--frameworks", type=Path, default=Path("../frameworks"))
    p.add_argument("--out", type=Path, default=Path("mapping.yaml"))
    args = p.parse_args(argv)

    mapping = build(args.frameworks)
    header = (
        "# scoring/mapping.yaml — evidence_type → [framework_id.control_id, ...]\n"
        "# Auto-generated by build_mapping.py from the framework registry.\n"
        "# Operators are expected to tune the entries below.\n"
        f"# Total evidence types: {len(mapping)}.\n"
    )
    args.out.write_text(
        header + yaml.safe_dump(mapping, sort_keys=False, allow_unicode=True, width=200),
        encoding="utf-8",
    )
    print(f"Wrote {len(mapping)} evidence types to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
