"""beacon-scan — the one-command engineer entrypoint, end to end.

The only assertion here that means anything is that the bundle `beacon-scan`
writes passes `src/beacon_verify.py`, the tool an AUDITOR runs. A producer that
verifies its own output proves nothing; these tests deliberately cross the
producer/verifier boundary, and one of them hides `cryptography` so the
verifier's pure-Python fallback — the thing that makes "nothing installed" true
— is exercised rather than assumed.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))


@pytest.fixture
def scanned(tmp_path, monkeypatch):
    """Run beacon-scan over a tree with two planted provenance markers."""
    beacon_home = tmp_path / "beacon-home"
    project = tmp_path / "project"
    project.mkdir()
    (project / "generated.py").write_text(
        "# Generated by claude-opus-5\ndef f():\n    pass\n", encoding="utf-8"
    )
    (project / "notes.md").write_text(
        "---\nai: true\nmodel: gpt-4o\n---\n\nnotes\n", encoding="utf-8"
    )
    (project / "plain.txt").write_text("nothing to see here\n", encoding="utf-8")

    monkeypatch.setenv("BEACON_HOME", str(beacon_home))
    # _common reads BEACON_HOME at import time, so it has to be reloaded after
    # the env var is set or every test would share the developer's real ~/.beacon.
    import importlib

    from beacons import _common

    importlib.reload(_common)
    import src.beacon_scan as beacon_scan

    importlib.reload(beacon_scan)

    bundle = tmp_path / "bundle"
    rc = beacon_scan.main(
        ["--path", str(project), "--out", str(bundle), "--no-egress"]
    )
    return {"rc": rc, "bundle": bundle, "project": project, "home": beacon_home}


def run_verifier(bundle: Path, *, env_extra: dict[str, str] | None = None):
    """Run the bundled verifier exactly as an auditor would."""
    env = dict(os.environ)
    env.pop("BEACON_HOME", None)
    if env_extra:
        env.update(env_extra)
    return subprocess.run(
        [sys.executable, "verify_bundle.py", "."],
        cwd=bundle,
        capture_output=True,
        text=True,
        env=env,
    )


def test_scan_exits_clean(scanned):
    assert scanned["rc"] == 0


def test_bundle_has_the_documented_layout(scanned):
    b = scanned["bundle"]
    for name in (
        "manifest.json",
        "manifest.sha256",
        "inventory.json",
        "VERIFY.md",
        "verify_bundle.py",
    ):
        assert (b / name).is_file(), f"missing {name}"
    assert (b / "receipts").is_dir()
    assert list((b / "public_keys").glob("*.pem")), "no public key shipped"


def test_the_auditors_verifier_accepts_the_bundle(scanned):
    """The whole point: a different tool, run the documented way, says OK."""
    r = run_verifier(scanned["bundle"])
    assert r.returncode == 0, r.stdout + r.stderr
    assert "beacon-verify: OK" in r.stdout


def test_it_verifies_with_no_dependencies_at_all(scanned, tmp_path):
    """VERIFY.md promises a bare Python 3 is enough. Hold it to that.

    A stub package that raises on import stands in for a machine without
    `cryptography`, forcing the verifier's pure-Python Ed25519 path.
    """
    blocker = tmp_path / "blocked"
    (blocker / "cryptography").mkdir(parents=True)
    (blocker / "cryptography" / "__init__.py").write_text(
        "raise ImportError('not available')\n", encoding="utf-8"
    )
    r = run_verifier(scanned["bundle"], env_extra={"PYTHONPATH": str(blocker)})
    assert r.returncode == 0, r.stdout + r.stderr
    assert "backend:  pure-python" in r.stdout, r.stdout


def test_manifest_digest_is_over_the_file_bytes(scanned):
    """`sha256sum -c manifest.sha256` has to actually pass.

    An earlier exporter recorded the digest of the manifest's CANONICAL form,
    which made the documented command fail on every bundle while the bundle was
    perfectly intact. Assert the sha256sum semantics, not just "a digit exists".
    """
    import hashlib

    b = scanned["bundle"]
    recorded, _, name = (
        (b / "manifest.sha256").read_text(encoding="utf-8").strip().partition("  ")
    )
    assert name == "manifest.json"
    actual = hashlib.sha256((b / "manifest.json").read_bytes()).hexdigest()
    assert recorded == actual


def test_inventory_is_derived_from_the_signed_receipts(scanned):
    """Every inventory row must trace to receipts — nothing hand-typed."""
    b = scanned["bundle"]
    inventory = json.loads((b / "inventory.json").read_text(encoding="utf-8"))
    assert inventory, "two planted markers should produce at least one row"

    receipts = []
    for f in (b / "receipts").glob("*.ndjson"):
        receipts += [json.loads(x) for x in f.read_text().splitlines() if x.strip()]
    assert len(receipts) == 2, "one receipt per planted marker, and none for plain.txt"

    assert sum(row["receipt_count"] for row in inventory) == len(receipts)
    for row in inventory:
        assert row["discovery_src"] == "beacon-scan"
        assert (row["vendor"], row["model"], row["version"]) != (None, None, None)


def test_a_tampered_receipt_is_caught(scanned):
    """Flip one byte of evidence; the auditor's tool must refuse the bundle."""
    b = scanned["bundle"]
    ndjson = next((b / "receipts").glob("*.ndjson"))
    entries = [json.loads(x) for x in ndjson.read_text().splitlines() if x.strip()]
    entries[0]["environment"] = "tampered"
    ndjson.write_text(
        "\n".join(json.dumps(e, ensure_ascii=False) for e in entries) + "\n",
        encoding="utf-8",
    )

    r = run_verifier(b)
    assert r.returncode != 0, "a tampered receipt verified — the check is worthless"
    assert "FAILED" in r.stdout + r.stderr


def test_receipts_carry_no_file_contents(scanned):
    """Privacy posture: metadata and hashes only, never payloads."""
    b = scanned["bundle"]
    raw = "\n".join(
        f.read_text(encoding="utf-8") for f in (b / "receipts").glob("*.ndjson")
    )
    assert "nothing to see here" not in raw
    assert "def f():" not in raw
    for entry in (json.loads(x) for x in raw.splitlines() if x.strip()):
        assert entry["prompt"] is None
        assert entry["result"] is None


def test_empty_scan_still_produces_a_valid_bundle(tmp_path, monkeypatch):
    """"Nothing found" is a real answer and must not be an error path."""
    import importlib

    monkeypatch.setenv("BEACON_HOME", str(tmp_path / "home"))
    from beacons import _common

    importlib.reload(_common)
    import src.beacon_scan as beacon_scan

    importlib.reload(beacon_scan)

    empty = tmp_path / "empty"
    empty.mkdir()
    bundle = tmp_path / "bundle-empty"
    rc = beacon_scan.main(["--path", str(empty), "--out", str(bundle), "--no-egress"])

    assert rc == 0
    manifest = json.loads((bundle / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["verification"]["receipts_failed"] == 0
    assert manifest["generated_by"] == "beacon-scan"


def test_a_missing_path_is_a_usage_error_not_a_crash(tmp_path, monkeypatch):
    monkeypatch.setenv("BEACON_HOME", str(tmp_path / "home"))
    import importlib

    import src.beacon_scan as beacon_scan

    importlib.reload(beacon_scan)
    assert beacon_scan.main(["--path", str(tmp_path / "nope"), "--no-egress"]) == 2


def test_egress_skip_is_reported_not_silently_counted_as_zero(scanned, monkeypatch):
    """"Never looked" must never render as "looked and found nothing"."""
    import src.beacon_scan as beacon_scan
    from beacons import model_beacon

    monkeypatch.setattr(model_beacon, "psutil", None, raising=False)
    count, reason = beacon_scan.scan_egress()
    assert count == 0
    assert reason and "psutil" in reason
